# Generated by Django 4.2.3 on 2023-07-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_column='mytitle', help_text='ENTER A VALID TITLE', max_length=50),
        ),
    ]
