# Generated by Django 4.2.3 on 2023-07-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(choices=[('A', 'پایتون'), ('B', 'جنگو')], default='A', max_length=50),
        ),
    ]
