# Generated by Django 4.2.3 on 2023-08-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='floatfield',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='myfile',
            field=models.FileField(null=True, upload_to='test'),
        ),
    ]
