# Generated by Django 4.2.3 on 2023-08-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_article_floatfield_article_myfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='myfile',
            field=models.FileField(blank=True, null=True, upload_to='test'),
        ),
    ]
